apiVersion: v1
kind: Secret
metadata:
{{- $secret_name := printf "%s-%s" (include "demoClient.fullname" .) "user" }}
  name: {{ $secret_name }}
type: Opaque
data:
  username: {{ .Values.webUser | b64enc }}
  # try to get the old secret
  # keep in mind, that a dry-run only returns an empty map 
  {{- $old_secret := lookup "v1" "Secret" .Release.Namespace $secret_name }}
  # check, if a secret is already set
  {{- if or (not $old_secret) (not $old_secret.data) }}
  # if not set, then generate a new password
  {{- $pass := default (randAlphaNum 20) .Values.demoClientWebPassword }}
  password: {{ $pass | b64enc }}
  {{ else }}
  # if set, then use the old value
  password: {{ index $old_secret.data "password" }}
  {{ end }}
