apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demoClient.fullname" . }}
  labels:
    {{- include "demoClient.labels" . | nindent 4 }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "demoClient.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "demoClient.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "demoClient.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DEMO_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ printf "%s-%s" (include "demoClient.fullname" .) "user" }}
            - name: DEMO_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ printf "%s-%s" (include "demoClient.fullname" .) "user" }}
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secretKey
                  name: {{ printf "%s-%s" (include "demoClient.fullname" .) "secret-key" }}
            - name: RMQ_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ printf "%s-%s" (include "demoClient.fullname" .) "rmq-credentials" }}
            - name: RMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ printf "%s-%s" (include "demoClient.fullname" .) "rmq-credentials" }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
