apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: demo-service
spec:
  vhost: "/"
  user: {{ .Values.rmqUser }} # name of the RabbitMQ user
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rmq
