apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/group.name: demo.harley.systems
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  name: rmq
spec:
  ingressClassName: alb
  rules:
  - 
    host: rabbitmq.demo.harley.systems
    http:
      paths:
      - backend:
          service:
            name: rmq
            port:
              name: management
        path: /
        pathType: Prefix
